### ISSUE TITLE
New allocation request, user selected blobbers

### ISSUE THREAD

**Issue by Sriep** [0chain/zboxcli#125]
New allocation is being changed so that the user selects the blobbers rather than 0chain. Whatever is needed to support that. Work with https://github.com/0chain/gosdk/issues/297 and https://github.com/0chain/0chain/issues/668.

**Comment by Sriep** [comment]
Moved https://github.com/0chain/zboxcli/issues/117 here. We still need to decide how the user finds a suitable selection of blobbers. 

Work with event database change https://github.com/0chain/0chain/pull/788

**Comment by dabasov** [comment]
fixed
