### ISSUE TITLE
Document collab related commands.

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/zboxcli#13]
There is an add-collab and delete-collab function for a file for collaboration with 3rd parties - pls check if we can list the collabs. Also, note that similarly we have a rx-pay option for a file for the receiver to pay for download for such a file by first creating a read pool for that allocation.

**Comment by andriykutsevol** [comment]
There is no list-collab function. 
To get the list you need some kind of state.
But it looks like zbox is stateless. 
Therefore, either zbox have to implement state, or it can be obtained from some source.

**Comment by guruhubb** [comment]
@andriykutsevol this is already looked at sorted. Check slack https://0chain.slack.com/archives/G014PQ61WNT/p1614112102007600 and https://0chain.slack.com/archives/G014PQ61WNT/p1613076865038400. But perhaps you can better document this on zboxcli and 0chainAPI.
