### ISSUE TITLE
Stop unwanted requests if the initial validation is not passed.

### ISSUE THREAD

**Issue by krishnemd** [0chain/zboxcli#130]
For example in the case of re-uploading an already existing file via CLI I can see that multiple chunk requests are hit on the server but instead we can minimize the overload and cost by not hitting the requests in the first place if its already existing or similar validation is failed in other cases too.
<img width="1026" alt="Screen Shot 2021-11-21 at 21 45 24" src="https://user-images.githubusercontent.com/34975245/142769453-4ee61810-2d28-471e-89ec-3f0b2dd39439.png">

**Comment by cnlangzi** [comment]
similar issue https://github.com/0chain/gosdk/issues/266
