### ISSUE TITLE
Sync command is unable to detect the file updates (changes) in local files

### ISSUE THREAD

**Issue by mohsenno1** [0chain/zboxcli#139]
the **update**(changes in local files) cannot be detected by **sync** command at all. No matter if it's in root or sub-folders.

Here is the test code:
https://github.com/0chain/system_test/blob/d8e998d7a19fc296807b2e662a87d3d99b2bb2e2/tests/cli_tests/zboxcli_sync_test.go#L22

The root cause seems to be in:
` allocationObj.GetAllocationDiff(localcache, localpath, filter, exclPath)`
https://github.com/0chain/gosdk/blob/31fb3d807c26923eba55300999944f7f0ffb5dbc/zboxcore/sdk/sync.go#L271

And the faulty function seems to be the **findDelta** in **gosdk**
https://github.com/0chain/gosdk/blob/31fb3d807c26923eba55300999944f7f0ffb5dbc/zboxcore/sdk/sync.go#L166

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/gosdk/pull/621
