### ISSUE TITLE
fix gosdk version in zbox

### ISSUE THREAD

**Issue by cnlangzi** [0chain/zboxcli#157]
```
./zbox version                                          08:34:37
0chain-core-sdk [INFO]   2022/01/20 08:34:43.726310 wallet.go:280: ******* Wallet SDK Version:v1.2.87 ******* (SetLogFile)
0box-sdk        [INFO]   2022/01/20 08:34:43.729222 sdk.go:72: ******* Storage SDK Version: v1.2.87 *******
0chain-core-sdk [INFO]   2022/01/20 08:34:45.551215 wallet.go:398: ******* Wallet SDK Version:v1.2.87 ******* (InitZCNSDK)
0box-sdk        [DEBUG]  2022/01/20 08:34:47.146864 networkworker.go:103: Get network result:{"miners":["https://dev.0chain.net/miner03","https://dev.0chain.net/miner01","https://dev.0chain.net/miner02"],"sharders":["https://dev.0chain.net/sharder02","https://dev.0chain.net/sharder01"]}
Version info:
	zbox....:  v1.0.4-21-ge33d846-dirty
	gosdk...:  v1.2.87
```

gosdk version is not updated properly in `make install`. please fix it. it should be updated with latest gosdk commit

1. check go.mod,
1. if gosdk is replaced with local path, please go to the local path, and get last commitid as gosdk version
1. if gosdk is not replaced, just use gosdk version in require section

**Comment by hackschnitzel09** [comment]
may this be the reason for issue #160 ?

**Comment by cnlangzi** [comment]
> may this be the reason for issue #160 ?

no. if `make install` doesn't work, some things should be missing on your local environment .

**Comment by patche-v** [comment]
@cnlangzi the issue here is the v1.2.87 version for gosdk?
I think that may be an issue with gosdk project
https://github.com/0chain/gosdk/blob/staging/core/version/version.go

**Comment by cnlangzi** [comment]
@patche-v  yes. it should be fixed like below steps

1. check go.mod,
1. if gosdk is replaced with local path, please go to the local path, and get last commitid as gosdk version
1. if gosdk is not replaced, just use gosdk version in require section

**Comment by princeparmar** [comment]
@cnlangzi For gosdk version we have one command
```sh
make getrev
```

this command changes the value of `VERSIONSTR` const in version package.
https://github.com/0chain/gosdk/blob/321351cfaa02382a5f4d2b7c29fe8a6fe41ec346/core/version/version.go#L5 const
https://github.com/0chain/gosdk/blob/321351cfaa02382a5f4d2b7c29fe8a6fe41ec346/Makefile#L50 command
