### ISSUE TITLE
make install not possible

### ISSUE THREAD

**Issue by hackschnitzel09** [0chain/zboxcli#160]
Hey, everytime I run make install I get errors.

cp $WORK/b263/_pkg_.a /home/kevin/.cache/go-build/8b/8b8c275f608ba0a9dec12ec0d67d6e48793657b69c8cefeb8ce0bcb29ed04305-d # internal
Makefile:30: recipe for target 'zbox' failed
make: *** [zbox] Error 2

**Comment by cnlangzi** [comment]
> 

@hackschnitzel09  could you try to run `make help` first? I guess `Makefile` doesn't work on your terminal.

**Comment by vincenzopalazzo** [comment]
this is a go env problem, please post your go version here and also the os used

**Comment by cnlangzi** [comment]
@hackschnitzel09 please check [here](https://github.com/0chain/zboxcli/blob/50e8923d256f85bbc932c5ea842fa9006c1d009d/.github/workflows/build-zbox.yaml#L13), it will show you how to build zbox on linux/window/macos
