### ISSUE TITLE
WIP: All the Allocations are not listing showing 

### ISSUE THREAD

**Issue by hm90121** [0chain/zboxcli#18]
When using ./zbox listallocations command sometimes it shows all the allocations, sometimes fewer than all allocations.The behaviour is random and is changing every few minutes

**Comment by andrenerd** [comment]
@hm90121 
thanks for reporting.
may i ask you to share the contents of these config files: 
- config.yaml
- network.yaml

ps. they are usually located in `~/.zcn` folder, if you are on linux/macos.

**Comment by hm90121** [comment]
config.yaml
```````````````````
---
block_worker: http://one.devnet-0chain.net/dns
signature_scheme: bls0chain
min_submit: 50
min_confirmation: 50
confirmation_chain_length: 3
max_txn_query: 5
query_sleep_time: 5

# # OPTIONAL - Uncomment to use/ Add more if you want
# preferred_blobbers:
#   - http://one.devnet-0chain.net:31051
#   - http://one.devnet-0chain.net:31052
#   - http://one.devnet-0chain.net:31053

``````````

there is no network.yaml file

**Comment by guruhubb** [comment]
@andrenerd @hm90121 use the verbose command and a network that has the latest code to get better error reporting. Btw, you only need config.yaml to point to different network.  If we are not using network.yaml raise issue to be taken out.

Only reason for random behavior could be that there are only 2 sharders. If they are not in sync, then you will get different data. So during query, we should change the logic and look at the response from both sharders and take the latest block response. @Kenwes13 can look at this

**Comment by guruhubb** [comment]
@bbist can you amend the logic as per above
