### ISSUE TITLE
Issue with download-cost calculation

### ISSUE THREAD

**Issue by lpoli** [0chain/zboxcli#196]
Download-cost calculation from zbox is used in system-tests.
Currently system-test for read-pool reduction checks for equality of same value before and after download, which itself is an issue that it is passing.

I uploaded zboxcli's `main.go` file which is `142 bytes` in `dev.0chain.net` network with `--data 2` and `--parity 2`. The download-cost returned by zboxcli was `13.613 uZcn`.
Blobber read-prices were:
```
  blobbers:
  - blobber_id:  0a58682c5314fcc160b2f17c3808de126a65ee2d5b0f77adbe0712fe83cb89b1
  - balance:     124.965 mZCN
  - blobber_id:  1717ae320f78e9798a21889b1a91d86c90110e3d1090debcd6c8ee5dc27a96f2
  - balance:     125.007 mZCN
  - blobber_id:  41a6d2c790776c06d6d0b1bb8bff394a9d8c273b4bd700e08db2c771a34b3a47
  - balance:     124.965 mZCN
  - blobber_id:  dfe99b25053106f3edd2517ec3f34ea719b9a7c6fc3ed09aca16050fd0aec515
  - balance:     125.007 mZCN

```

After downloading `main.go` read-pool balance reduced from `500 mZCN` to `499.946 mZCN` which is download-cost is `0.054 mZCN`
Instead `zbox get-download-cost` returned `13.613 uZCN` which is lesser than `0.054 mZCN`.

**Comment by sculptex** [comment]
@lpoli it occurs to me that 0.054 mZCN is 54 uZCN which is roughly 4x 13.613 uZCN. And there are 4 blobbers total. But not sure where logic is wrong.

**Comment by lpoli** [comment]
> @lpoli it occurs to me that 0.054 mZCN is 54 uZCN which is roughly 4x 13.613 uZCN. And there are 4 blobbers total. But not sure where logic is wrong.

I think 13.613 uZcn is also for 4 blobbers. Not for single blobber
