### ISSUE TITLE
show raw/friendly error message if dns is down 

### ISSUE THREAD

**Issue by cnlangzi** [0chain/zboxcli#237]
It is json error instead of raw/friendly error. It is confused. 

<img width="1070" alt="Screen Shot 2022-05-24 at 09 36 33" src="https://user-images.githubusercontent.com/347651/169931004-61a6e212-bf49-464f-92c8-9e4674982397.png">

**Comment by sculptex** [comment]
I believe there should be support for multiple dns entries for redundancy. In which case, a random one should be chosen each time and in case of error (invalid JSON), another tried.

**Comment by cnlangzi** [comment]
> I believe there should be support for multiple dns entries for redundancy. In which case, a random one should be chosen each time and in case of error (invalid JSON), another tried.

@guruhubb is asking to improve HA for 0dns.
