### ISSUE TITLE
zbox sync does not detect changes in subdirectories

### ISSUE THREAD

**Issue by stewartie4** [0chain/zboxcli#250]
Steps to reproduce:
- create allocation
- create local folder with a subdirectory
- add file to root folder and subdirectory 
- if the root file is updated then the file and subdirectories are synced 
- If the file in the subdirectory is updated then nothing is synced

See more here:
https://0chain.slack.com/archives/G014PQ61WNT/p1638477374103000

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/gosdk/pull/621
