### ISSUE TITLE
Zbox move and copy returns a zero exit code on error

### ISSUE THREAD

**Issue by stewartie4** [0chain/zboxcli#251]
Zbox move and copy returns a zero exit code on error.
This could lead to a script or other orchestrator believing the operation was successful when it was not 

Fix: 
on ./zbox copy and ./zbox move, if an operation fails, return a non-zero exit code

**Comment by cnlangzi** [comment]
@Hassaan008  the PR is not merged yet. I would suggest to leave issue with github workflow. it will be closed once the related PR is merged.

**Comment by boddumanohar** [comment]
I am sorry, When I checked last night, the PR status was shown as closed. So I though the PR might have merged so I asked Hassan to close it. Sure lets follow the github work and will double check the PR before closing the issue.
