### ISSUE TITLE
Keeping --verbose flag true by default for CLI.

### ISSUE THREAD

**Issue by chauchausoup** [0chain/zboxcli#27]
SInce it takes some time to execute the CLI command, it might be less efficient to make user wait in unknown. With --verbose default to true we can make CLI screen look more interactive. Sometime even if the CLI returns success command in the brackground there might be erronous log going on as in this example, which will be not unknown to a user/developer with --verbose enabled.

![Screenshot from 2021-06-04 22-18-10](https://user-images.githubusercontent.com/34975245/120834605-f6aec000-c582-11eb-9503-3e7f1dfbc961.png)
Due to following reasons I think we should make --verbose true by default. 
Please share your thoughts on it.
Thank you.

**Comment by guruhubb** [comment]
I agree.  Use another flag to hide details of all SC transactions. @bbist @Sriep

**Comment by chauchausoup** [comment]
Here is a[ PR](https://github.com/0chain/zboxcli/pull/33) for the issue.

**Comment by sculptex** [comment]
I missed this one, if command output is JSON then this breaks it?

**Comment by moldis** [comment]
--json instead of --verbose

**Comment by sculptex** [comment]
yes, so if --json option is selected then output has to be valid json. but depending on command output capture method, error is separate to default terminal so could be excluded. but nett screen output includes debug so json is invalid.

we kinda agreed to keep until mainnet so I will continue to use --silent so close it if you like. just make --silent silently deprecated when it is dropped (so it doesn't give error)
