### ISSUE TITLE
Change to give new blobber fields.

### ISSUE THREAD

**Issue by Sriep** [0chain/zboxcli#28]
[blobber table](https://seven.devnet-0chain.net/blobber) and [blobber diagnostic](https://seven.devnet-0chain.net/blobber06/_stats) pages need new “allocated capacity” and “total tokens staked”  fields. 

Matches gosdk change https://github.com/0chain/gosdk/issues/87

**Comment by andrenerd** [comment]
Related to https://github.com/0chain/blobber/issues/127
