### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by Sriep** [0chain/zboxcli#29]
Transfer ownership of allocation by current owner or curatorID to new owner.

Matched with gosdk issue https://github.com/0chain/gosdk/issues/89

**Comment by andrenerd** [comment]
It mostly duplicates:
https://github.com/0chain/0chain/issues/333

**Comment by guruhubb** [comment]
@andrenerd make sure that both current owner and curator are able to transfer ownership of owner's allocation to new owner/buyer. cc @Sriep

**Comment by guruhubb** [comment]
@andrenerd @Sriep we can have a command, ./zbox add curator $ID --alloc $ALLOC to allow curator to transfer allocation.

**Comment by Sriep** [comment]
Handled by https://github.com/0chain/zboxcli/pull/47
