### ISSUE TITLE
Read pool balance is not affected by download cost if download via auth ticket.

### ISSUE THREAD

**Issue by nlok5923** [0chain/zboxcli#300]
Test `"Share encrypted file using auth ticket - download accounting test - proxy re-encryption ` and `Share unencrypted file using auth ticket - download accounting test` in TestShareFile at `system_test` skipped due to download cost not affecting readpool balance.

Info: 
- When a file is shared by owner wallet to receiver wallet using auth ticket and on download file using the receiver wallet after staking tokens in read pool (by receivers wallet) no decrease in read pool balance is observed when download is done using the receiver wallet even though download cost is not zero and blobbers read price is non zero.

Refer to this issue: https://github.com/0chain/system_test/issues/364

**Comment by Kishan-Dhakan** [comment]
Closed by https://github.com/0chain/0chain/pull/1721
