### ISSUE TITLE
Multi-payer write pool

### ISSUE THREAD

**Issue by Sriep** [0chain/zboxcli#31]
Use payerID to allow multiple payers for allocation. Upon expiry, unused tokens can go back to payerID. Need gosdk/zboxcli changes.

Matched with gosdk issue https://github.com/0chain/gosdk/issues/88

**Comment by andrenerd** [comment]
It's probably linked to:
https://github.com/0chain/blobber/pull/162
https://github.com/0chain/0chain/pull/347

PS. i guess the title is misleading. write pools are strictly linked to specific users.

**Comment by guruhubb** [comment]
Title is fine. Yes, you're right that a write pool is owned by a user. But multiple people should be able to use payerID to lock tokens.

**Comment by guruhubb** [comment]
Make sure ./zbox wp-lock allows any payer to lock tokens for the allocation. Then this feature already exists and we don't need to do anything. @andrenerd @Sriep

**Comment by Sriep** [comment]
[writePoolLock](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/writepool.go#L337) is the endpont for `./zbox wp-lock`.  Inspecting the code, It looks like anyone can lock tokens,  we could add a unit test to  https://github.com/0chain/0chain/issues/323 to confirm this point.

**Comment by Sriep** [comment]
PR https://github.com/0chain/0chain/pull/389 should fix this issue. 
Closed and Moved to https://github.com/0chain/0chain/issues/385.
