### ISSUE TITLE
zbox copy command not consistent with linux copy command

### ISSUE THREAD

**Issue by boddumanohar** [0chain/zboxcli#331]
in linux 
```
$ cp file.txt dir1/
cp: directory dir1 does not exist
```

in zbox cli
```
zbox copy --allocation $alloc --remotepath /17.png --destpath /bap
```
we are creating `bap` folder and uploading content into that folder

in linux:
```
$ cp file.txt dir/file.txt #this will create a new file with name `file.txt` in dir folder
```

in zbox cli `destpath` only supports folders only it doesn't support actual filenames

in linux:
```
$ cp dir1/* dir2/
```

in zbox cli we cannot copy all the files in one folder to another

**Comment by boddumanohar** [comment]
@Manish-210 @dabasov 
requirements: 
1. when the path provided in `--destpath` doesn't exist, we should return error telling `dest path does not exist`

2. another requirement is (but it might not be possible under the current design of the zboxcli/gosdk):

in linux cli, if I run `cp ./file.txt dir/file2.txt` it actually creates a new file name `file2.txt` in `dir` folder. 
but in zbox cli, since `destpath` only accepts folder names, the above syntax is not possible.

**Comment by peterlimg** [comment]
@boddumanohar we will need to run another command to manually create dest dir if it does not exit. Which means user will pay extra fee for copying a file. @lpoli please help to check if we should return error when dest path does not exist.

**Comment by lpoli** [comment]
@boddumanohar 
> zbox copy --allocation $alloc --remotepath /17.png --destpath /bap

It is considered a feature to create directory if it does not exist. Also it is not uploaded but copy operation is applied. Same story with upload operation, it creates required directories.

And yes we cannot move or copy into different name.

Also about your last concern, I don't think it is right. You can copy all the files from one directory to another.

**Comment by boddumanohar** [comment]
thanks for the clarification @lpoli. In that case, the task mentioned in the ticket need not be solved as we can consider creating a folder if doesn't exist a feature.
