### ISSUE TITLE
Update allocation with --expiry flag not working.

### ISSUE THREAD

**Issue by chauchausoup** [0chain/zboxcli#34]
Update allocation with --size flag works fine for now. It adds to the previous size value of the allocation. This might be another issue too ( Update means to replace the previous size value by the given value instead of adding the given to previous, right? )
Update allocation with --expiry flag gives "Error updating allocation:transaction_not_found: Transaction was not found on any of the sharders" error.
Here is a ss to the CLI with --expiry flag.
![update_allocation_expiry_error](https://user-images.githubusercontent.com/34975245/121514459-c5634380-ca0b-11eb-856f-7d2c455a4745.png)

**Comment by guruhubb** [comment]
Have you checked if the transaction is recorded on the blockchain by searching the Explorer. Its possible the timeout is shorter. Check the sdk and increase the timeout for sharder calls.

**Comment by chauchausoup** [comment]
I did checked the transaction and it seem to record on blockchain with assigned size and expiry time.

**Comment by stewartie4** [comment]
@guruhubb regressions updated but they are failing.
Seeing the same on explorer with a brand new wallet 
![image](https://user-images.githubusercontent.com/18306778/121782569-0ee59700-cba2-11eb-86eb-85845fe7f2af.png)

**Comment by chauchausoup** [comment]
`./zbox updateallocation --allocation d8b3ac2377ddf526a9710768a3db3d11bde8a5acce4e3576a338e027126f796d --size 3000000000`
It adds upto the previous size of the allocaiton. Is that an expected behaviour?

`./zbox updateallocation --allocation d8b3ac2377ddf526a9710768a3db3d11bde8a5acce4e3576a338e027126f796d --size 3000000000 --expiry 200h0m0s `
Gives Error updating allocation:transaction_not_found: Transaction was not found on any of the sharders error.

This means we have error only with --expiry flag?
Can someone confirm by checking in the CLI at their end?

**Comment by guruhubb** [comment]
Yes you can increase or decrease size and expiry - see example in https://github.com/0chain/0chain/tree/master/code/go/0chain.net/smartcontract/storagesc#initial

Make sure the transaction with expiry did not happen by searching it on the Explorer. And that the hours did not go beyond the blobbers max configuration.

cc @andrenerd

**Comment by Sriep** [comment]
I tried to reproduce this issue and initially failed
```
./zbox updateallocation --allocation 4ebed4311317d73c6d46e4e3d33410ef8e229e5d848893bd1f9bf09c2f0d7cd6 --size 2097152 --expiry -3.5h --verbose
0chain-core-sdk [INFO]   2021/06/24 09:44:22.695864 wallet.go:276: ******* Wallet SDK Version:v1.2.6 *******
0box-sdk [INFO]   2021/06/24 09:44:22.695932 sdk.go:69: ******* Storage SDK Version: v1.2.6 *******
0chain-core-sdk [INFO]   2021/06/24 09:44:22.696560 wallet.go:359: *******  Wallet SDK Version:v1.2.6 *******
0box-sdk [DEBUG]  2021/06/24 09:44:22.697293 networkworker.go:98: Get network result:{"miners":["http://192.168.1.100:7071","http://192.168.1.76:7071","http://192.168.1.95:7071"],"sharders":["http://192.168.1.100:7171"]}
Allocation updated with txId : d6727d582171de2af9d53e82c9a973319cc78791df99b96b5fb2c7eac9e4bd38
```
Then i tried exactly the same transaction and manged to reproduce the porblem
```
./zbox updateallocation --allocation 4ebed4311317d73c6d46e4e3d33410ef8e229e5d848893bd1f9bf09c2f0d7cd6 --size 3000000000 --expiry 200h0m0s --verbose
0chain-core-sdk [INFO]   2021/06/24 09:46:11.387190 wallet.go:276: ******* Wallet SDK Version:v1.2.6 *******
0box-sdk [INFO]   2021/06/24 09:46:11.387241 sdk.go:69: ******* Storage SDK Version: v1.2.6 *******
0chain-core-sdk [INFO]   2021/06/24 09:46:11.387913 wallet.go:359: *******  Wallet SDK Version:v1.2.6 *******
0box-sdk [DEBUG]  2021/06/24 09:46:11.388529 networkworker.go:98: Get network result:{"miners":["http://192.168.1.100:7071","http://192.168.1.76:7071","http://192.168.1.95:7071"],"sharders":["http://192.168.1.100:7171"]}
0box-sdk [ERROR]  2021/06/24 09:47:11.408404 sdk.go:1007: Error verifying the transactiontransaction_not_found: Transaction was not found on any of the sharders3f6da4a180788ae00378b9742abc7ebccd52a9a41f66c1e7df2aa6d646e3a851
Error creating allocation:transaction_not_found: Transaction was not found on any of the sharders
```
On examing the logs I found
```json
{
  "txn": {
    "hash": "3f6da4a180788ae00378b9742abc7ebccd52a9a41f66c1e7df2aa6d646e3a851",
    "version": "1.0",
    "client_id": "ee69de2635ae40977c099a5c21cabb580263199d8925c7f2789870fb007265c3",
    "to_client_id": "6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7",
    "chain_id": "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe",
    "transaction_data": "{\"name\":\"update_allocation_request\",\"input\":{\"expiration_date\":720000,\"id\":\"4ebed4311317d73c6d46e4e3d33410ef8e229e5d848893bd1f9bf09c2f0d7cd6\",\"owner_id\":\"ee69de2635ae40977c099a5c21cabb580263199d8925c7f2789870fb007265c3\",\"size\":3000000000}}",
    "transaction_value": 0,
    "signature": "fa70082cbad056871af3cd1eb0591b532f60f88891421732d38451528404c21f",
    "creation_date": 1624524371,
    "transaction_fee": 0,
    "transaction_type": 1000,
    "txn_output_hash": "",
    "transaction_status": 0
  },
  "error": "allocation_extending_failed: blobber 2a4d5a5c6c0976873f426128d2ff23a060ee715bccf0fd3ca5e987d57f25b78e doesn't have enough free space"
}
```
There was not enough space on the blobber, so user error. 

The real culprit would appear to be bad error reporting, with real reason for errors being replaced with a generic `Transaction was not found on any of the sharders`. I have raised a new issue to this efferct.

**Comment by Sriep** [comment]
@chauchausoup could you confirm insufficient space on the blobber was the problem. If so I suggest close this issue and replace with https://github.com/0chain/zboxcli/issues/53

**Comment by chauchausoup** [comment]
@Sriep can you help me with where you were able to view such log ?

**Comment by chauchausoup** [comment]
@Sriep this suerly is not a issue related to actual updateallocation as I was able to update allocation with some constraint. 
If I update with expiry negative value then they work fine but on updating with +ve expiry this update allocation gives us error as state above. 
But on consecutive -ve and +ve update to allocation works fine. 
There must be other reasons to this and definitly error reporting on specific reason is the way around.
So I am closing the issue for now and refering the issue to https://github.com/0chain/zboxcli/issues/53

**Comment by stewartie4** [comment]
I think this needs re-opened 
API regressions are failing due to inability to update
https://0chain.github.io/blobber/feature_add-api-regressions-to-ci/latest/

**Comment by andrenerd** [comment]
@stewartie4 
where to check the testing code? 
it looks like it was ABLE (not "unable") to update as the response code is ok (200). isn't it?

**Comment by stewartie4** [comment]
The response code was 200 ok but the subsequent confirmation on the sharder failed ￼with 

{
    "code": "entity_not_found",
    "error": "entity_not_found: txn_summary not found with id = 3c1830dc4be1be9021da607131fda2898f6accacbd03453afc5ef556d49a25fb"
}

**Comment by andrenerd** [comment]
@stewartie4 
Imo, it's not enough.
It's needed to see the testing code/params to reproduce and debug the case.
Where it's possible to check the code?

**Comment by shaktals** [comment]
It seems like this continues to be [a problem](https://github.com/0chain/block-explorer/issues/205) on explorer. I'm opening this up again.
