### ISSUE TITLE
[FEATURE] Add `continuous download` feature 

### ISSUE THREAD

**Issue by cnlangzi** [0chain/zboxcli#49]
for now, we have a feature `dowload by blocks`. but you have to calculate blockNums and blockIndex, and loop it till done. `download` has to restart from scratch if network is broken. A new `continuous download` should be added
- automatically download it with blocks
- continuous download from last breakpoint when network is back or ./zbox download is restarted 
- parallel download all blocks from all blobbers

related to https://github.com/0chain/gosdk/issues/314

**Comment by sculptex** [comment]
I don't understand:-
* parallel download all blocks from all blobbers

Each chunk is already downloaded in parallel, adding additional instances of multiple chunks is self-defeating purpose of continuous/partial download

**Comment by lpoli** [comment]
Since this is related to https://github.com/0chain/gosdk/issues/314, I am closing it here.
