### ISSUE TITLE
failed libc dependency on latest build

### ISSUE THREAD

**Issue by sculptex** [0chain/zboxcli#520]
new failed dependencies experienced with v1.10.0 on ubuntu 18 and 20

* ./zbox: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./zbox)
* ./zbox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./zbox)
* ./zbox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./zbox)

**Comment by boddumanohar** [comment]
@Kishan-Dhakan can you please take a look at this issue. Seems to be happening on machines with older gcc version. We might need to update documentation or provide a new make target that installs the required gcc version.

**Comment by sculptex** [comment]
I don't know why this was closed, pretty sure windows external dll requirements are unrelated to linux builds. I tried building sprint1.11 from source in case fixed but wont build for me. If indeed fixed, please push new release or advise how to build.

**Comment by boddumanohar** [comment]
Hi @sculptex, the associated PR only solves the issue for windows builds. To run Linux binaries, it requires: `GLIBCXX_3.4.29` to be present on the system. This will be available from ubuntu 22.02.


Currently we are using ubuntu 22.02, Because of this, it requires, atleast `GLIBCXX_3.4.29` 

To fix this issue, we can start building the binaires from ubuntu 20.02. That will add support for ubuntu 20 and 22. 

Since the binaries depend very much on the underlying OS libraries. We cannot support ubuntu 18.

**Comment by sculptex** [comment]
> Hi @sculptex, the associated PR only solves the issue for windows builds. To run Linux binaries, it requires: `GLIBCXX_3.4.29` to be present on the system. This will be available from ubuntu 22.02.
> 
> Currently we are using ubuntu 22.02, Because of this, it requires, atleast `GLIBCXX_3.4.29`
> 
> To fix this issue, we can start building the binaires from ubuntu 20.02. That will add support for ubuntu 20 and 22.
> 
> Since the binaries depend very much on the underlying OS libraries. We cannot support ubuntu 18.

Ok, thanks. Please can zbox and zwallet releases be pushed that work with Ubuntu 20 then? Also ensure documentatikn reflects this.

**Comment by boddumanohar** [comment]
@sculptex We've update the git actions runners to use ubuntu20 and also updated the documentation. 

If you would like to try the latest build, you could download it from the artifacts here: 
https://github.com/0chain/zboxcli/actions/runs/6854787069

Please note that, on Ubuntu 20, the default gcc version is 9. But for zboxcli binaries to work, it requires at least gcc 11. So please follow this updated documentation to update the gcc version. 

https://github.com/0chain/zboxcli/wiki/Install-zboxcli#linux-installation

**Comment by sculptex** [comment]
@boddumanohar Hey, thanks. I followed the gcc instructions on a ubuntu20 installation (that was previously working) and was subsequently able to build and run the tools successfully.
