### ISSUE TITLE
Zbox latest windows release doesnot work out of the box

### ISSUE THREAD

**Issue by hm90121** [0chain/zboxcli#522]
Downloading the zbox windows.zip from here https://github.com/0chain/zboxcli/releases
and extracting it for running gives error where as adding dlls from here https://github.com/0chain/zboxcli/files/11840033/windows.dll.s.zip in the extracted directory works

Can any body add dlls or make it work out of the box ?

**Comment by boddumanohar** [comment]
https://github.com/0chain/zboxcli/actions/runs/6931435265

Please download the latest windows.zip from this git action.

The latest windows.zip will be releases on the sprint release
