### ISSUE TITLE
Unable to upload the file on Zboxcli windows dev msi 64

### ISSUE THREAD

**Issue by HassanAbbas7357** [0chain/zboxcli#535]
`cuteh@Hassan-PC MINGW64 ~/zboxcli
$ ./zbox upload --localpath /home/cuteh/zboxcli/opd.txt --remotepath /myfiles/opd.txt --allocation ac6f1e0bcf39d89eb2c36d4f1c96414d4f52b716dd6deb76f72bca7da24cc42d
0chain-core-sdk [INFO]   2023/10/28 22:20:56.491486 wallet_base.go:329: ******* Wallet SDK Version:v1.8.17-78-g80b63345 ******* (SetLogFile)
0box-sdk        [INFO]   2023/10/28 22:20:56.491486 sdk.go:78: ******* Storage SDK Version: v1.8.17-78-g80b63345 *******
0chain-core-sdk [INFO]   2023/10/28 22:20:56.929500 transaction_base.go:140: ******* Wallet SDK Version:v1.8.17-78-g80b63345 ******* (InitZCNSDK)
0box-sdk        [DEBUG]  2023/10/28 22:20:57.355285 networkworker.go:105: Get network result:{"miners":["https://dev2.zus.network/miner01","https://dev3.zus.network/miner01","https://dev1.zus.network/miner01"],"sharders":["https://dev2.zus.network/sharder01","https://dev3.zus.network/sharder01","https://dev1.zus.network/sharder01"]}
Upload failed. invalid_path: Path should be valid and absolute
`

**Comment by hm90121** [comment]
@HassanAbbas7357 this is windows mingw64 directory issue some steps has to be added

**Comment by hm90121** [comment]
@HassanAbbas7357 added some additional steps https://github.com/0chain/zboxcli/wiki/Build-Windows

run the zbox commands under windows powershell now to fix this issue.
