### ISSUE TITLE
Unable to perform file operations  on windows dev such as Createdir

### ISSUE THREAD

**Issue by HassanAbbas7357** [0chain/zboxcli#536]
![image](https://github.com/0chain/zboxcli/assets/49572299/9f7c3269-8582-4cbc-9a19-57eb54f33466)

**Comment by hm90121** [comment]
@HassanAbbas7357 this is windows mingw64 directory issue 
some additional steps has to be added.

**Comment by hm90121** [comment]
@HassanAbbas7357 added some additional steps https://github.com/0chain/zboxcli/wiki/Build-Windows

run the zbox commands under windows powershell now to fix this issue.
