### ISSUE TITLE
No file appears when i list down the files and gives duplicate error on upload

### ISSUE THREAD

**Issue by HassanAbbas7357** [0chain/zboxcli#537]
I upload a file name file.jpg and then i list down but nothing appeared and then when i tried to reupload it showed me the dupl,icate file upload error 
![image](https://github.com/0chain/zboxcli/assets/49572299/c301f94b-705a-44ce-8f02-de6f11985392)

**Comment by hm90121** [comment]
@guruhubb  @HassanAbbas7357 
List files is fixed when updating zboxcli from staging to sprint.
I faced the same issue on dev with zboxcli staging.Please see thread below.
https://0chain.slack.com/archives/C03788G8N2D/p1698226612017929

Please assign @Jayashsatolia403 for zboxcli staging fix.

**Comment by Jayashsatolia403** [comment]
@guruhubb This is fixed in sprint. @hm90121 was using staging with sprint deployed network so was facing this issue. 

Closing it.
