### ISSUE TITLE
ZBOXCLI missing DLL files or missing instructions in the gitbook

### ISSUE THREAD

**Issue by HassanAbbas7357** [0chain/zboxcli#538]
I have downloaded the zboxcli from [GitbookLink](https://docs.zus.network/guides/zbox-cli/get-started#:~:text=Download%20the%20latest%20windows%20zboxcli%20archive%20release%20from%20here.) these are the missing dll files which needs to be present in the zboxcli folder before running the zboxcli ,
previously there were steps to copy paste the dll files from repo and paste into the zboxcli but those steps are missing now either we should include those files in the folder or write the steps explicitly

![image](https://github.com/0chain/zboxcli/assets/49572299/f4b5d409-d6fa-476b-8502-a1a6eb9d9baa)
![image](https://github.com/0chain/zboxcli/assets/49572299/aa89c199-27b1-4e11-bc5b-e13f4d51777a)

**Comment by boddumanohar** [comment]
https://github.com/0chain/zboxcli/actions/runs/6931435265

we don't have windows.zip in the releases. But we can download it from the latest git action

**Comment by boddumanohar** [comment]
just tested with the zip file from the above git action. working fine. Closing it.
