### ISSUE TITLE
Unclaimed Rewards vs Total Rewards in sp-info

### ISSUE THREAD

**Issue by Trevor-K-Smith** [0chain/zboxcli#576]
This value should read "total rewards".

This value, unless im wrong, it the total rewards over lifetime of the blobber. Not unclaimed rewards.

![image](https://github.com/0chain/zboxcli/assets/28652769/d8e03973-d773-4989-a4b2-fadff8d03215)

**Comment by Zorro30** [comment]
Since its rewards is returned in json form, renaming uncliamed rewards to rewards while printing on terminal
PR 
https://github.com/0chain/zboxcli/pull/586
