### ISSUE TITLE
[ERROR ENHANCEMENT]Copy to root doesn’t seem to work if there are no folders.

### ISSUE THREAD

**Issue by haule24hdev** [0chain/zboxcli#67]
![Screenshot from 2021-07-26 14-41-35](https://user-images.githubusercontent.com/50743635/126951707-79d7ca5e-c847-48c0-894e-7791af55d87c.png)
![Screenshot from 2021-07-26 14-42-31](https://user-images.githubusercontent.com/50743635/126951718-70d7e416-5cf9-4644-a243-bf14099a8326.png)
![Screenshot from 2021-07-26 14-42-45](https://user-images.githubusercontent.com/50743635/126951724-430165d8-fde8-4d43-ad97-1b6ed19049e0.png)

**Comment by Sriep** [comment]
The first screenshot shows a file at /2.txt. The second screenshot shows you trying to overwrite the /2.txt. So it looks like the correct issue is that you can't overwrite a file while copying to root.

I reproduced this locally. by double sending a copy to root. The first worked the second one did not with `"Invalid destination path. Object Already exists`.

So should you be able to overwrite while copying?

**Comment by haule24hdev** [comment]
@Sriep, yes. But can you make to return a good error ?
![Screenshot from 2021-07-29 08-52-41](https://user-images.githubusercontent.com/50743635/127419276-fe2dde07-3ba2-4029-a32a-9a7cb325e3f0.png)

**Comment by haule24hdev** [comment]
I pinged Siva but he's not available?

**Comment by cnlangzi** [comment]
it will be fixed on https://github.com/0chain/blobber/pull/491
