### ISSUE TITLE
Zbox Installation fails on M1 (arm64) 

### ISSUE THREAD

**Issue by NoSkillGuy** [0chain/zboxcli#78]
```
go build -x -v -tags bn256 -ldflags "-X main.VersionStr=v1.0.1-237-g5585dc4-dirty" -o zbox main.go
WORK=/var/folders/h4/60lytm6s0_jcmddzht1lhq2r0000gp/T/go-build1021085998
github.com/herumi/bls-go-binary/bls
mkdir -p $WORK/b055/
cd /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls
TERM='dumb' CGO_LDFLAGS='"-g" "-O2" "-lbls384_256" "-lstdc++" "-lm" "-L/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/lib/darwin/arm64"' /opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64/cgo -objdir $WORK/b055/ -importpath github.com/herumi/bls-go-binary/bls -- -I $WORK/b055/ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include ./bls.go ./callback.go ./mcl.go
cd $WORK
clang -fno-caret-diagnostics -c -x c - -o /dev/null || true
clang -Qunused-arguments -c -x c - -o /dev/null || true
clang -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
clang -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd $WORK/b055
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -o ./_x001.o -c _cgo_export.c
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -o ./_x002.o -c bls.cgo2.c
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -o ./_x003.o -c callback.cgo2.c
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -o ./_x004.o -c mcl.cgo2.c
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -I/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/include -o ./_cgo_main.o -c _cgo_main.c
cd /Users/noskillguy/workspace/0chain/zboxcli
TERM='dumb' clang -I /Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b055=/tmp/go-build -gno-record-gcc-switches -fno-common -o $WORK/b055/_cgo_.o $WORK/b055/_cgo_main.o $WORK/b055/_x001.o $WORK/b055/_x002.o $WORK/b055/_x003.o $WORK/b055/_x004.o -g -O2 -lbls384_256 -lstdc++ -lm -L/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/lib/darwin/arm64
# github.com/herumi/bls-go-binary/bls
ld: warning: directory not found for option '-L/Users/noskillguy/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20191119080710-898950e1a520/bls/lib/darwin/arm64'
ld: library not found for -lbls384_256
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [zbox] Error 2
```

**Comment by NoSkillGuy** [comment]
This is because `bls-go-binary` doesn't have a darwin/arm64 binary in it. 

raised a PR in `bls-go-binary` adding `darwin/arm64` binary - [here](https://github.com/herumi/bls-go-binary/pull/5) . So while building Zbox on `darwin/arm64` architecture. we need to pull this specific commit (124ee283019e963ff3cd0cfdc8f9e8dae7bc2339) to solve the problem. 

```
go get github.com/herumi/bls-go-binary@124ee283019e963ff3cd0cfdc8f9e8dae7bc2339
```

@Sriep should I update the `bls-go-binary` version in Zbox and raise a PR ? 

since we were using a very old version `bls-go-binary@v0.0.0-20191119080710-898950e1a520` updating to latest `v1.22` might break something, I don't have much idea

**Comment by cnlangzi** [comment]
It works on&nbsp;Harshit Mehndiratta Mac&nbsp;



From&nbsp;mobile&nbsp;


------------------ Original ------------------
From: NoSkillGuy ***@***.***&gt;
Date: Sat, Aug 7, 2021 8:21 PM
To: 0chain/zboxcli ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [0chain/zboxcli] Zbox Installation fails on M1 (arm64)  (#78)





 
This is because bls-go-binary doesn't have a darwin/arm64 binary in it.
 
raised a PR in bls-go-binary adding darwin/arm64 binary - here . So while building Zbox on darwin/arm64 architecture. we need to pull this specific commit (124ee283019e963ff3cd0cfdc8f9e8dae7bc2339) to solve the problem.
 go get ***@***.***  
@Sriep should I update the bls-go-binary version in Zbox and raise a PR ?
 
since we were using a very old version ***@***.*** updating to latest v1.22 might break something, I don't have much idea
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NoSkillGuy** [comment]
@cnlangzi didn't get you. Are you saying it works without this change?
If so I don't think so that's possible, since `bls-go-binary` doesn't have `darwin/arm64` binary in their repo.

**Comment by cnlangzi** [comment]
Yes. We get it worked with go mod replace. It might be go mod issue



From&nbsp;mobile&nbsp;


------------------ Original ------------------
From: NoSkillGuy ***@***.***&gt;
Date: Sat, Aug 7, 2021 8:31 PM
To: 0chain/zboxcli ***@***.***&gt;
Cc: Lz ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [0chain/zboxcli] Zbox Installation fails on M1 (arm64)  (#78)





 
@cnlangzi didn't get you. Are you saying it works without this change?
 If so I don't think so that's possible, since bls-go-binary doesn't have darwin/arm64 binary in their repo.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rsivapraveen001** [comment]
How can it work without `bls-go-binary` having `darwin/arm64` binary? 

Have you guys complied `bls-go-binary` and generated `darwin/arm64` binary and then updated in GOPATH?

**Comment by cnlangzi** [comment]
No. We just git clone https://github.com/herumi/bls-go-binary on local. and `make` it. And replace go mod with local path. It works on @hm90121 's Mac Mini . you can have a try.

**Comment by cnlangzi** [comment]
I can't find why. Because I have not Mac with M1. you can have a try, and find why and how to fix it.

**Comment by NoSkillGuy** [comment]
when you `make` it, you are essentially creating a binary on the M1 machine right, so that's `darwin/arm64` you have build it. 
Then you are replacing in go mod with the local path. 

So I fixed it. I have created the binary and raised a PR in `bls-go-binary` [here](https://github.com/herumi/bls-go-binary/pull/5), which upon merging would solve the problem. Then we need to use the latest version of `bls-go-binary` in our repo.

**Comment by hm90121** [comment]
@NoSkillGuy are u able to create allocations using zboxcli on your m1 mac?

**Comment by NoSkillGuy** [comment]
@hm90121 Yes, I am able to

**Comment by NoSkillGuy** [comment]
Closing this issue with the following solutions. 

> We just git clone https://github.com/herumi/bls-go-binary on local. and `make` it. And replace go mod with local path. It works on @hm90121 's Mac Mini . you can have a try.



> This is because `bls-go-binary` doesn't have a darwin/arm64 binary in it.
> 
> raised a PR in `bls-go-binary` adding `darwin/arm64` binary - [here](https://github.com/herumi/bls-go-binary/pull/5) . So while building Zbox on `darwin/arm64` architecture. we need to pull this specific commit (124ee283019e963ff3cd0cfdc8f9e8dae7bc2339) to solve the problem.
> 
> ```
> go get github.com/herumi/bls-go-binary@124ee283019e963ff3cd0cfdc8f9e8dae7bc2339
> ```
> 
> @Sriep should I update the `bls-go-binary` version in Zbox and raise a PR ?
> 
> since we were using a very old version `bls-go-binary@v0.0.0-20191119080710-898950e1a520` updating to latest `v1.22` might break something, I don't have much idea
