### ISSUE TITLE
Update code to remove bls library on windows

### ISSUE THREAD

**Issue by cnlangzi** [0chain/zboxcli#86]
Remove herumi/bls from zbox.exe, or embedded it in zbox.exe . Please test it  on a fresh windows install instead of local development window.

```
Libstdc++-6.dll, libgcc_s_seh-1.dll, libwinpthread-1.dll
```

linked to https://github.com/0chain/zwalletcli/issues/37

**Comment by guruhubb** [comment]
Once we have merged the wasm sdk from Andika, this issue won't be there.

**Comment by cnlangzi** [comment]
it is impossible now. wasm sdk is working with bls wasm. it is not supported on windows.
